### ISSUE TITLE
[EOSi Frontend] #1 This heading should be...

### ISSUE THREAD

**Issue by webrgp** [dative/eosi-frontend-mix#10]
This heading should be contaminants treated - the nav link and subnav menus for contaminants and customers is backwards.

*Source url:* https://eosi-frontend.netlify.app/
*Reported by:* Chris ()
*Reported at:* 06 Jul at 14:00 UTC

*Type:* Feedback

*Location:* US, Massachusetts, Buzzards Bay
*Browser:* Firefox 102.0
*User Agent:* Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0
*OS:* macOS 10.15
*Screen:* 2560x1440
*Viewport:* 1463x795
*Referrer:* https://eosi-frontend.netlify.app/sds-form.html
*Screenshot:*
![Screenshot](https://ybug.io/data/reports/2jthgkzzyyyb1mp45m3r/1nn77afpv5xz7dwvphnk/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTcxMTYwNjEsImRhdGEiOnsicmVwb3J0IjoiMW5uNzdhZnB2NXh6N2R3dnBobmsiLCJ1c2VyIjoiR2l0SHViIn19.LQVfsYHNj_04-IwunoHj3lgZxyMILF8KwpJycjovXOc)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/1nn77afpv5xz7dwvphnk](https://ybug.io/dashboard/reports/detail/1nn77afpv5xz7dwvphnk)

**Comment by diegocosta-dev** [comment]
I got this one <3
