### ISSUE TITLE
[EOSi Frontend] #2 Remove the prefilled text in the...

### ISSUE THREAD

**Issue by webrgp** [dative/eosi-frontend-mix#11]
Remove the prefilled text in the fields

*Source url:* https://eosi-frontend.netlify.app/lead-form.html
*Reported by:* Chris ()
*Reported at:* 06 Jul at 14:01 UTC

*Type:* Feedback

*Location:* US, Massachusetts, Buzzards Bay
*Browser:* Firefox 102.0
*User Agent:* Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0
*OS:* macOS 10.15
*Screen:* 2560x1440
*Viewport:* 1390x798
*Referrer:* https://eosi-frontend.netlify.app/lead-form.html
*Screenshot:*
![Screenshot](https://ybug.io/data/reports/2jthgkzzyyyb1mp45m3r/0sp5kyw907z2wb9mxnab/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTcxMTYxMjAsImRhdGEiOnsicmVwb3J0IjoiMHNwNWt5dzkwN3oyd2I5bXhuYWIiLCJ1c2VyIjoiR2l0SHViIn19.vqKubcRqKpHGPTsKTPTvv1dIKHAnSeGj7RGlHzAPS34)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/0sp5kyw907z2wb9mxnab](https://ybug.io/dashboard/reports/detail/0sp5kyw907z2wb9mxnab)

**Comment by diegocosta-dev** [comment]
I got this one <3
