### ISSUE TITLE
[EOSi Frontend] #3 Add more space above and below...

### ISSUE THREAD

**Issue by webrgp** [dative/eosi-frontend-mix#12]
Add more space above and below this section

*Source url:* https://eosi-frontend.netlify.app/why-eosi.html
*Reported by:* Chris ()
*Reported at:* 06 Jul at 14:07 UTC

*Type:* Feedback

*Location:* US, Massachusetts, Buzzards Bay
*Browser:* Firefox 102.0
*User Agent:* Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0
*OS:* macOS 10.15
*Screen:* 2560x1440
*Viewport:* 1369x735
*Referrer:* https://eosi-frontend.netlify.app/
*Screenshot:*
![Screenshot](https://ybug.io/data/reports/2jthgkzzyyyb1mp45m3r/0zqvv36h0tnp5j69s1ds/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTcxMTY0NDIsImRhdGEiOnsicmVwb3J0IjoiMHpxdnYzNmgwdG5wNWo2OXMxZHMiLCJ1c2VyIjoiR2l0SHViIn19.YMCyE9Tnhbm9YfI_d1cuieq61pHTc-eZkBwfte1Ecxo)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/0zqvv36h0tnp5j69s1ds](https://ybug.io/dashboard/reports/detail/0zqvv36h0tnp5j69s1ds)

**Comment by diegocosta-dev** [comment]
I got this one <3
