### ISSUE TITLE
[EOSi Frontend] #4 replace this list with the text...

### ISSUE THREAD

**Issue by webrgp** [dative/eosi-frontend-mix#16]
replace this list with the text that I will attach to the issue.

*Source url:* https://eosi-frontend.netlify.app/company.html
*Reported by:* Chris ()
*Reported at:* 06 Jul at 16:17 UTC

*Type:* Feedback

*Location:* US, Massachusetts, Buzzards Bay
*Browser:* Firefox 102.0
*User Agent:* Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0
*OS:* macOS 10.15
*Screen:* 2560x1440
*Viewport:* 1439x754
*Referrer:* https://eosi-frontend.netlify.app/nitrack.html
*Screenshot:*
![Screenshot](https://ybug.io/data/reports/2jthgkzzyyyb1mp45m3r/pmc0zzmdh4hpz7t6qc98/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTcxMjQyMzksImRhdGEiOnsicmVwb3J0IjoicG1jMHp6bWRoNGhwejd0NnFjOTgiLCJ1c2VyIjoiR2l0SHViIn19.Tu8iET77EnT1GvxoNaURxOvqBZRG28NfplNWzxHf31k)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/pmc0zzmdh4hpz7t6qc98](https://ybug.io/dashboard/reports/detail/pmc0zzmdh4hpz7t6qc98)

**Comment by chrisobs13** [comment]
Thomas J. Walkosak
CEO
Tom’s 25 years of leading and managing industry-leading environmental services and water treatment chemical businesses include experience as General Manager of USP Technologies, a Trojan/Danaher company providing environmental technology, equipment, and chemical service programs, VP and member of the Trojan Technologies Executive Team, and key management positions with global chemical producer FMC Corporation. 


Samuel Ledwell
President
Joining EOSi at the company’s 2003 inception, Sam has more than two decades industry-leadership experience with biological contaminant removal technologies, products, and services, specifically focused on developing EOSi’s MicroC® product portfolio of carbon sources and Nitrack® equipment and services. 


Jeffrey Prellberg
Vice President, Sales & Marketing
Jeff brings more than 30 years of water/wastewater treatment industry experience, including senior positions as Director of Global Service and Aftermarket and VP Municipal Business Development with Trojan Technologies, a Danaher company providing water and wastewater treatment technology and service solutions, and as part of the senior management team for Danaher’s USP Technologies business.


Rob Keeling
Vice President, Operations
With more than 15 years of experience in supplier development, supply chain management, procurement, and operations, Rob manages EOSi’s global supplier development, raw material identification and procurement, risk management, rail-car fleet, inbound rail and truck logistics, and new manufacturing site development for our nationwide network of production facilities.


Ryan Coleman, P.E., LEED AP
Director, Process Solutions & Programs
A Professional Engineer registered in the state of Idaho, Ryan’s extensive wastewater operations and process knowledge includes hands-on experience in the protein industry, and managing industrial wastewater treatment plants for several companies in Colorado, Idaho, and Pennsylvania. Ryan led a series of BNR optimization initiatives successfully reducing effluent total nitrogen concentrations by more than 97 percent as Cargill, Inc.’s Environmental Manager, and managed construction and operation of facilities creating renewable clean energy from dairy waste.


Sandra L. Clark
Director, Quality Management Systems
An ASQ Certified Manager of Quality and Organizational Excellence and ASQ Certified Quality Engineer, Sandra’s more than 25 years of quality management experience enables expanding and developing EOSi’s new quality processes to support product manufacturing, raw materials procurement, meeting and exceeding customer expectations, and creating value through company’s quality management system. 


Michelle Murray 
Senior Accountant
With a dozen years of corporate accounting experience with EOSi, Design Mark Industries, and Calgreg Electronics, Michelle’s senior accountant responsibilities include processing all financial transactions, accounts receivable, accounts payable, and payroll duties, tax filing coordination with CPAs, creating specialized financial presentations, and compiling and presenting financial information for annual reports.

**Comment by diegocosta-dev** [comment]
I got this one!

**Comment by webrgp** [comment]
Fixed on https://github.com/dative/eosi-frontend-mix/pull/27
