### ISSUE TITLE
[EOSi Frontend] #8 Replace with text that I will...

### ISSUE THREAD

**Issue by webrgp** [dative/eosi-frontend-mix#21]
Replace with text that I will add to this issue.

*Source url:* https://eosi-frontend.netlify.app/product-template.html
*Reported by:* Chris ()
*Reported at:* 06 Jul at 16:38 UTC

*Type:* Feedback

*Location:* US, Massachusetts, Buzzards Bay
*Browser:* Firefox 102.0
*User Agent:* Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0
*OS:* macOS 10.15
*Screen:* 2560x1440
*Viewport:* 1447x743
*Referrer:* https://eosi-frontend.netlify.app/product-template.html
*Screenshot:*
![Screenshot](https://ybug.io/data/reports/2jthgkzzyyyb1mp45m3r/78fxrrrkrcw1msqkxga0/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTcxMjU1NTIsImRhdGEiOnsicmVwb3J0IjoiNzhmeHJycmtyY3cxbXNxa3hnYTAiLCJ1c2VyIjoiR2l0SHViIn19.j0HXi9aMMi4nSLANaujR8Ec6bo2eeMsUDG_9gHzaU0k)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/78fxrrrkrcw1msqkxga0](https://ybug.io/dashboard/reports/detail/78fxrrrkrcw1msqkxga0)

**Comment by diegocosta-dev** [comment]
I got this one

**Comment by webrgp** [comment]
Fixed on https://github.com/dative/eosi-frontend-mix/pull/28
