### ISSUE TITLE
[EOSi Frontend] #10 The page gap shold be 3rem/48px

### ISSUE THREAD

**Issue by webrgp** [dative/eosi-frontend-mix#23]
The page gap shold be 3rem/48px

*Source url:* https://eosi-frontend.netlify.app/nitrack
*Reported by:* Diego Costa ()
*Reported at:* 06 Jul at 17:32 UTC

*Type:* Improvement

*Location:* BR, Rio Grande do Norte, Natal
*Browser:* Chrome 103.0.5060.66
*User Agent:* Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.66 Mobile Safari/537.36 Edg/103.0.1264.44
*OS:* Android 6.0
*Screen:* 1460x739
*Viewport:* 1460x739

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/2jthgkzzyyyb1mp45m3r/w4b6mscbvn81wks7wgz4/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTcxMjg3NzQsImRhdGEiOnsicmVwb3J0IjoidzRiNm1zY2J2bjgxd2tzN3dnejQiLCJ1c2VyIjoiR2l0SHViIn19.PyNK8cGfEkTYD5cnQiyG69ltXm7H_cnT0Y72xq9CIrU)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/w4b6mscbvn81wks7wgz4](https://ybug.io/dashboard/reports/detail/w4b6mscbvn81wks7wgz4)

**Comment by diegocosta-dev** [comment]
I got this one

**Comment by webrgp** [comment]
Fixed on https://github.com/dative/eosi-frontend-mix/pull/31
