### ISSUE TITLE
[EOSi Frontend] #12 Use file attached in comment to...

### ISSUE THREAD

**Issue by webrgp** [dative/eosi-frontend-mix#25]
Use file attached in comment to replace the FAQ questions/answers.

*Source url:* https://eosi-frontend.netlify.app/faqs.html
*Reported by:* Chris ()
*Reported at:* 06 Jul at 18:14 UTC

*Type:* Feedback

*Location:* US, Massachusetts, Buzzards Bay
*Browser:* Firefox 102.0
*User Agent:* Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0
*OS:* macOS 10.15
*Screen:* 2560x1440
*Viewport:* 1396x765
*Referrer:* https://eosi-frontend.netlify.app/company.html
*Screenshot:*
![Screenshot](https://ybug.io/data/reports/2jthgkzzyyyb1mp45m3r/jqrd462pvdh2awcsy4yn/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTcxMzEyNzksImRhdGEiOnsicmVwb3J0IjoianFyZDQ2MnB2ZGgyYXdjc3k0eW4iLCJ1c2VyIjoiR2l0SHViIn19.YkYcaP6WEb16OqpFdrFR8QI3VFQ5E0qI5-NIPS765TA)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/jqrd462pvdh2awcsy4yn](https://ybug.io/dashboard/reports/detail/jqrd462pvdh2awcsy4yn)

**Comment by chrisobs13** [comment]
[EOSI website v2 - Why EOSi-FAQ subpage - 4-19-2022 v1-1.pdf](https://github.com/dative/eosi-frontend-mix/files/9057139/EOSI.website.v2.-.Why.EOSi-FAQ.subpage.-.4-19-2022.v1-1.pdf)

**Comment by webrgp** [comment]
Fixed on https://github.com/dative/eosi-frontend-mix/pull/30
