### ISSUE TITLE
[EOSi Frontend] #17 Card body should not be links

### ISSUE THREAD

**Issue by webrgp** [dative/eosi-frontend-mix#36]
Card body should not be links

*Source url:* https://eosi-frontend.netlify.app/microc.html
*Reported by:* Chris ()
*Reported at:* 07 Jul at 13:29 UTC

*Type:* Feedback

*Location:* US, Massachusetts, Buzzards Bay
*Browser:* Firefox 102.0
*User Agent:* Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0
*OS:* macOS 10.15
*Screen:* 2560x1440
*Viewport:* 1393x723
*Referrer:* https://eosi-frontend.netlify.app/product-template.html
*Screenshot:*
![Screenshot](https://ybug.io/data/reports/2jthgkzzyyyb1mp45m3r/jk307w1ttk0cx743tm48/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTcyMDA2MDMsImRhdGEiOnsicmVwb3J0IjoiamszMDd3MXR0azBjeDc0M3RtNDgiLCJ1c2VyIjoiR2l0SHViIn19.Bin_wEJINb3mgg5Es-T0MkAfeykVi5T-gfd51mIDTxQ)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/jk307w1ttk0cx743tm48](https://ybug.io/dashboard/reports/detail/jk307w1ttk0cx743tm48)

**Comment by diegocosta-dev** [comment]
I got this one
