### ISSUE TITLE
[EOSi Frontend] #18 Center this button on entire form

### ISSUE THREAD

**Issue by webrgp** [dative/eosi-frontend-mix#37]
Center this button on entire form

*Source url:* https://eosi-frontend.netlify.app/sds-form.html
*Reported by:* Chris ()
*Reported at:* 07 Jul at 13:31 UTC

*Type:* Feedback

*Location:* US, Massachusetts, Buzzards Bay
*Browser:* Firefox 102.0
*User Agent:* Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0
*OS:* macOS 10.15
*Screen:* 2560x1440
*Viewport:* 1393x723
*Referrer:* https://eosi-frontend.netlify.app/sds-form-detail
*Screenshot:*
![Screenshot](https://ybug.io/data/reports/2jthgkzzyyyb1mp45m3r/ymwhyqtnrhkgtg7xkz8h/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTcyMDA3MDAsImRhdGEiOnsicmVwb3J0IjoieW13aHlxdG5yaGtndGc3eGt6OGgiLCJ1c2VyIjoiR2l0SHViIn19.2apc6CN_Tgl_FZeQZzg7rvwWPCgll2w-0zFXeeRtK0Y)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/ymwhyqtnrhkgtg7xkz8h](https://ybug.io/dashboard/reports/detail/ymwhyqtnrhkgtg7xkz8h)

**Comment by diegocosta-dev** [comment]
> @diegocosta-dev in mobile, fields should stack as a column.

okay, I'll fix it tomorrow

**Comment by diegocosta-dev** [comment]
@webrgp was fixed!
