### ISSUE TITLE
[EOSi Frontend] #20 For the numbers, add a "count up...

### ISSUE THREAD

**Issue by webrgp** [dative/eosi-frontend-mix#39]
For the numbers, add a "count up" style JS effect.

For example: 

 https://inorganik.github.io/countUp.js/

*Source url:* https://eosi-frontend.netlify.app/why-eosi.html
*Reported by:* Chris ()
*Reported at:* 07 Jul at 14:48 UTC

*Type:* Feedback

*Location:* US, Massachusetts, Buzzards Bay
*Browser:* Firefox 102.0
*User Agent:* Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0
*OS:* macOS 10.15
*Screen:* 2560x1440
*Viewport:* 1341x726
*Referrer:* https://eosi-frontend.netlify.app/industry-template.html
*Screenshot:*
![Screenshot](https://ybug.io/data/reports/2jthgkzzyyyb1mp45m3r/qyhgvhw08z9g1mw6d2qb/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTcyMDUzMDMsImRhdGEiOnsicmVwb3J0IjoicXloZ3ZodzA4ejlnMW13NmQycWIiLCJ1c2VyIjoiR2l0SHViIn19.vq2ciZ4QEn06FvNyXWQr4gNYWgswnmPORXdTZvrAP10)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/qyhgvhw08z9g1mw6d2qb](https://ybug.io/dashboard/reports/detail/qyhgvhw08z9g1mw6d2qb)

**Comment by diegocosta-dev** [comment]
I tried to do this <3

**Comment by diegocosta-dev** [comment]
I tried creating it this way, I'm having a problem, scrolling down doesn't work, just scrolling up works, I don't know how to reverse scroll

@webrgp 

```` js
import { CountUp } from 'countup.js';

const init = ( selector: string ) => {
  const elements = document.querySelectorAll( selector );
  elements.forEach((el) => {
    const countUp = new CountUp(el.id, parseFloat(el.innerHTML), {suffix: "+", enableScrollSpy: true});
    !countUp.error ? countUp.start() : console.error(countUp.error);
    countUp.handleScroll(countUp);
  });
}

init('[data-count]')
````

**Comment by webrgp** [comment]
I will take a look.

**Comment by webrgp** [comment]
I decided to just straight up write our own function because the library was too generic and added too much bloat.

Also, it didn't format the numbers with commas.
