### ISSUE TITLE
[EOSi Frontend] #21 All these footer links should go...

### ISSUE THREAD

**Issue by webrgp** [dative/eosi-frontend-mix#41]
All these footer links should go to the lead form page:

https://eosi-frontend.netlify.app/lead-form.html

*Source url:* https://eosi-frontend.netlify.app/why-eosi.html#
*Reported by:* Chris ()
*Reported at:* 07 Jul at 14:49 UTC

*Type:* Feedback

*Location:* US, Massachusetts, Buzzards Bay
*Browser:* Firefox 102.0
*User Agent:* Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0
*OS:* macOS 10.15
*Screen:* 2560x1440
*Viewport:* 1341x726
*Referrer:* https://eosi-frontend.netlify.app/industry-template.html
*Screenshot:*
![Screenshot](https://ybug.io/data/reports/2jthgkzzyyyb1mp45m3r/xgsvhhzzhxn98hwrwh2q/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTcyMDUzNTgsImRhdGEiOnsicmVwb3J0IjoieGdzdmhoenpoeG45OGh3cndoMnEiLCJ1c2VyIjoiR2l0SHViIn19.Agm0whZzEEWkgjDiXcU2xF52dJM4YtQJVg-JPicHcdk)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/xgsvhhzzhxn98hwrwh2q](https://ybug.io/dashboard/reports/detail/xgsvhhzzhxn98hwrwh2q)

**Comment by diegocosta-dev** [comment]
I got this one
