### ISSUE TITLE
[EOSi Frontend] #23 For all "accordion" components,...

### ISSUE THREAD

**Issue by webrgp** [dative/eosi-frontend-mix#43]
For all "accordion" components, make text within the area smaller - 18px

*Source url:* https://eosi-frontend.netlify.app/why-eosi.html
*Reported by:* Chris ()
*Reported at:* 07 Jul at 14:55 UTC

*Type:* Feedback

*Location:* US, Massachusetts, Buzzards Bay
*Browser:* Firefox 102.0
*User Agent:* Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0
*OS:* macOS 10.15
*Screen:* 2560x1440
*Viewport:* 1341x726
*Referrer:* https://eosi-frontend.netlify.app/industry-template.html

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/2b8f35q9r7fyh6br2aya](https://ybug.io/dashboard/reports/detail/2b8f35q9r7fyh6br2aya)

**Comment by diegocosta-dev** [comment]
I got this one
