### ISSUE TITLE
[EOSi Frontend] #26 the accordions in safari, are...

### ISSUE THREAD

**Issue by webrgp** [dative/eosi-frontend-mix#55]
the accordions in safari, are showing the content ºarrow

*Source url:* https://eosi-frontend.netlify.app/faqs
*Reported by:* Diego Costa ()
*Reported at:* 11 Jul at 17:16 UTC

*Type:* Bug
*Console:* [1× Log](https://ybug.io/dashboard/reports/detail/h3jhm75w9jfq1kj8n434#console)

*Location:* BR, Rio Grande do Norte, Natal
*Browser:* Safari 15.3
*User Agent:* Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Safari/605.1.15
*OS:* macOS 10.15.7
*Screen:* 1920x1080
*Viewport:* 1510x642

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/2jthgkzzyyyb1mp45m3r/h3jhm75w9jfq1kj8n434/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTc1NTk4MTMsImRhdGEiOnsicmVwb3J0IjoiaDNqaG03NXc5amZxMWtqOG40MzQiLCJ1c2VyIjoiR2l0SHViIn19.QR7hacfF178MC-NG9Stx-Xb_ZrsMCpJ3mOVNMIlht2I)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/h3jhm75w9jfq1kj8n434](https://ybug.io/dashboard/reports/detail/h3jhm75w9jfq1kj8n434)

**Comment by diegocosta-dev** [comment]
![image](https://user-images.githubusercontent.com/48633894/178321049-5e99d857-6758-4efa-9099-42fd949824ba.png)

**Comment by diegocosta-dev** [comment]
I got this one

**Comment by webrgp** [comment]
fixed
