### ISSUE TITLE
[EOSi Frontend] #27 The cards on the nitrack page,...

### ISSUE THREAD

**Issue by webrgp** [dative/eosi-frontend-mix#56]
The cards on the nitrack page, are with this bug.

*Source url:* https://eosi-frontend.netlify.app/nitrack
*Reported by:* Diego Costa ()
*Reported at:* 11 Jul at 17:26 UTC

*Type:* Bug
*Console:* [1× Log](https://ybug.io/dashboard/reports/detail/9rny461z5wda2qjfnxgr#console)

*Location:* BR, Rio Grande do Norte, Natal
*Browser:* Safari 15.3
*User Agent:* Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Safari/605.1.15
*OS:* macOS 10.15.7
*Screen:* 1920x1080
*Viewport:* 1510x642

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/2jthgkzzyyyb1mp45m3r/9rny461z5wda2qjfnxgr/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTc1NjAzOTksImRhdGEiOnsicmVwb3J0IjoiOXJueTQ2MXo1d2RhMnFqZm54Z3IiLCJ1c2VyIjoiR2l0SHViIn19.s51X0aeF8wl_IYNGvq0rheKXKwScg1rvDp1Enyw2Bl4)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/9rny461z5wda2qjfnxgr](https://ybug.io/dashboard/reports/detail/9rny461z5wda2qjfnxgr)

**Comment by diegocosta-dev** [comment]
The cards on the nitrack page, are with this bug.

![image](https://user-images.githubusercontent.com/48633894/178322607-4192904c-3ad6-4834-816a-87296c25bc25.png)
