### ISSUE TITLE
[EOSi Frontend] #28 The same bugs in the nitrack...

### ISSUE THREAD

**Issue by webrgp** [dative/eosi-frontend-mix#57]
The same bugs in the nitrack page #56, the cards are with this problem.

*Source url:* https://eosi-frontend.netlify.app/why-eosi
*Reported by:* Diego Costa ()
*Reported at:* 11 Jul at 17:40 UTC

*Type:* Bug
*Console:* [1× Log](https://ybug.io/dashboard/reports/detail/q37qhbgyp7ayv9kf5wcm#console)

*Location:* BR, Rio Grande do Norte, Natal
*Browser:* Safari 15.3
*User Agent:* Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Safari/605.1.15
*OS:* macOS 10.15.7
*Screen:* 1920x1080
*Viewport:* 1510x642

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/2jthgkzzyyyb1mp45m3r/q37qhbgyp7ayv9kf5wcm/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTc1NjEyMjcsImRhdGEiOnsicmVwb3J0IjoicTM3cWhiZ3lwN2F5djlrZjV3Y20iLCJ1c2VyIjoiR2l0SHViIn19.BxqgySD7Z3Ji4xwq8Act2BosCEV9FKVsK1jkH8Vu3y8)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/q37qhbgyp7ayv9kf5wcm](https://ybug.io/dashboard/reports/detail/q37qhbgyp7ayv9kf5wcm)

**Comment by diegocosta-dev** [comment]
![image](https://user-images.githubusercontent.com/48633894/178324944-a030897e-6735-40df-a330-dad9bcd0ba4e.png)
