### ISSUE TITLE
[EOSi Frontend] #30 Make this icon larger

### ISSUE THREAD

**Issue by webrgp** [dative/eosi-frontend-mix#59]
Make this icon larger

*Source url:* https://eosi-frontend.netlify.app/
*Reported by:* Chris ()
*Reported at:* 11 Jul at 19:07 UTC

*Type:* Feedback

*Location:* US, Massachusetts, Buzzards Bay
*Browser:* Firefox 102.0
*User Agent:* Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0
*OS:* macOS 10.15
*Screen:* 2560x1440
*Viewport:* 1437x797
*Referrer:* https://eosi-frontend.netlify.app/microc.html
*Screenshot:*
![Screenshot](https://ybug.io/data/reports/2jthgkzzyyyb1mp45m3r/w13mwh2n5xbdg2myfcnb/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTc1NjY0NTUsImRhdGEiOnsicmVwb3J0IjoidzEzbXdoMm41eGJkZzJteWZjbmIiLCJ1c2VyIjoiR2l0SHViIn19.LLAW8JcaEMybQHHdnZrowNmptVYrckRDNmyG1O5CGVU)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/w13mwh2n5xbdg2myfcnb](https://ybug.io/dashboard/reports/detail/w13mwh2n5xbdg2myfcnb)

**Comment by diegocosta-dev** [comment]
@chrisobs13 The play icon should be 25px, is that it?

![image](https://user-images.githubusercontent.com/48633894/178503384-379830f8-8dbc-460a-bff8-63443c324b0c.png)

**Comment by chrisobs13** [comment]
@diegocosta-dev Sorry this was a test showing the client how to add feedback. You can disregard.
