### ISSUE TITLE
[EOSi Frontend] #31 Remove Tom from list

### ISSUE THREAD

**Issue by webrgp** [dative/eosi-frontend-mix#60]
Remove Tom from list

*Source url:* https://eosi-frontend.netlify.app/company.html
*Reported by:* Chris ()
*Reported at:* 11 Jul at 19:15 UTC

*Type:* Feedback

*Location:* US, Massachusetts, Buzzards Bay
*Browser:* Firefox 102.0
*User Agent:* Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0
*OS:* macOS 10.15
*Screen:* 2560x1440
*Viewport:* 1437x797
*Referrer:* https://eosi-frontend.netlify.app/
*Screenshot:*
![Screenshot](https://ybug.io/data/reports/2jthgkzzyyyb1mp45m3r/b3p2qajzpm0bgj9c1czv/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTc1NjY5MzIsImRhdGEiOnsicmVwb3J0IjoiYjNwMnFhanpwbTBiZ2o5YzFjenYiLCJ1c2VyIjoiR2l0SHViIn19.6mhrEpfVfuub1JNMm0TnEG4Ac3eBXSy97Rfi0VIj9Lw)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/b3p2qajzpm0bgj9c1czv](https://ybug.io/dashboard/reports/detail/b3p2qajzpm0bgj9c1czv)

**Comment by diegocosta-dev** [comment]
I got this one
