### ISSUE TITLE
[EOSi Frontend] #32 Update video link with new video

### ISSUE THREAD

**Issue by webrgp** [dative/eosi-frontend-mix#61]
Update video link with new video

https://www.youtube.com/watch?v=xebX7tof6l4

*Source url:* https://eosi-frontend.netlify.app/
*Reported by:* Chris ()
*Reported at:* 11 Jul at 19:29 UTC

*Type:* Feedback

*Location:* US, Massachusetts, Buzzards Bay
*Browser:* Firefox 102.0
*User Agent:* Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0
*OS:* macOS 10.15
*Screen:* 2560x1440
*Viewport:* 1322x797
*Referrer:* https://eosi-frontend.netlify.app/product-template.html
*Screenshot:*
![Screenshot](https://ybug.io/data/reports/2jthgkzzyyyb1mp45m3r/kcpjn1dqdk3gjf4yj8ft/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTc1Njc4MDIsImRhdGEiOnsicmVwb3J0Ijoia2Nwam4xZHFkazNnamY0eWo4ZnQiLCJ1c2VyIjoiR2l0SHViIn19.w8K0RaX1BgC0NytvVzOrEUV0InvKYQuHNe6P-ALwGWA)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/kcpjn1dqdk3gjf4yj8ft](https://ybug.io/dashboard/reports/detail/kcpjn1dqdk3gjf4yj8ft)

**Comment by diegocosta-dev** [comment]
I got this one

**Comment by webrgp** [comment]
added
