### ISSUE TITLE
[EOSi Frontend] #33 Remove email link and icon

### ISSUE THREAD

**Issue by webrgp** [dative/eosi-frontend-mix#62]
Remove email link and icon

*Source url:* https://eosi-frontend.netlify.app/
*Reported by:* Chris ()
*Reported at:* 11 Jul at 19:35 UTC

*Type:* Feedback

*Location:* US, Massachusetts, Buzzards Bay
*Browser:* Firefox 102.0
*User Agent:* Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0
*OS:* macOS 10.15
*Screen:* 2560x1440
*Viewport:* 1322x797
*Referrer:* https://eosi-frontend.netlify.app/product-template.html
*Screenshot:*
![Screenshot](https://ybug.io/data/reports/2jthgkzzyyyb1mp45m3r/d81a3q55zb907g15wp91/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTc1NjgxNDEsImRhdGEiOnsicmVwb3J0IjoiZDgxYTNxNTV6YjkwN2cxNXdwOTEiLCJ1c2VyIjoiR2l0SHViIn19.evk2FJ5fjEjVffrPKj_nts2yr51uI63Fa5FdviTaPHQ)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/d81a3q55zb907g15wp91](https://ybug.io/dashboard/reports/detail/d81a3q55zb907g15wp91)

**Comment by diegocosta-dev** [comment]
I got this one

**Comment by chrisobs13** [comment]
Client wants to put icon back and have it be a mailto: link
